config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resource :profile, only: [:edit, :update, :show]
  resources :playgrounds, only: [:index, :new, :create, :show]
  resources :events do
    resources :playgrounds, only: [:create, :edit]
  end

  namespace :playgrounds do
    resources :events, only: [:index, :show]

    resources :events, only: [] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  # belongs_to :playground
  geocoded_by :location, presence: true, uniqueness: true
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/playground.rb
class Playground < ApplicationRecord
  has_many :events
  has_one_attached :image
  geocoded_by :location, presence: true, uniqueness: true
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/profile.rb
class Profile < ApplicationRecord
  skills = %w[
    drills
    jump
    power
    speed
    dunks
    3pts
    independence
    communication
    teamwork
    creativity
    initiative
    stress_management
    perseverance
    decision_making
    adaptability
    enthusiam
    flexibility
  ]
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  has_one_attached :profile_pic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
      }
  end
end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @playground = Playground.new
    @playgrounds = @event.playground
  end

   def create
    @event = Event.new(event_params)
    if @event.save!
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :price, :reward, :image, :playground_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def index
    @playgrounds = Playground.all

    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @playgrounds.map do |playground|
       {
        lat: playground.latitude,
        lng: playground.longitude
      }
    end
  end

  def create
    @playground = Playground.new(playground_params)
    if @playground.save!
      redirect_to playground_path(@playground)
    else
      render :new
    end
  end

  def new
    @playground = Playground.new
  end

  def show
    @playground = Playground.find(params[:id])
    @event = Event.new
    @events = @playground.events
  end

  private

  def playground_params
    params.require(:playground).permit(:name, :location, :reputation, :status, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    # @user = profile.nick_name
  end

  def show
    # @user = profile.nick_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/events/_event_card.html.erb
<%= link_to event_path(event) do %>
  <div class="card-event">
    <div class="card-event-infos">
      <div>
        <h2><%= event.name %></h2>
        <h2><%= event.location %></h2>
        <h2><%= event.playground_id %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/events/create.html.erb
<a class="link"><%=link_to "Home", root_path%></a>

app/views/events/edit.html.erb
<h1>Make your event</h1>
<a class="link"><%=link_to "Home", root_path%></a>

app/views/events/index.html.erb
<a class="link"><%=link_to "Add an event", new_event_path%></a>

<div id="map"
     style="width: 50%; height: 400px; margin-left: auto; margin-right:auto;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class ="container-1">
  <% @events.each do |event| %>
  <%= render "event_card", event: event %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="text-center">New Event</h1>

<div class="pt-30 container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@event) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :location %>
          <%= f.input :playground %>
          <%= f.input :price %>
          <%= f.input :reward %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
  <a class="link"><%=link_to "Home", root_path%></a>

</div>

app/views/events/show.html.erb
<a class="link"><%=link_to "Playgrounds", playgrounds_path%></a>
<a class="link"><%=link_to "Events", events_path%></a>



<div class="container-event">
  <div class="information-event">
  <h1><%= @event.name %></h1>
  <h2><%= @event.location %></h2>
  <h2><%= @event.price %>$</h2>
  <h2><%= @event.reward %>$</h2>
  <h2><%= @event.date %>$</h2>
  </div>
  <div class ="subscription">
    <h3><%= link_to "Subscribe here", root_path %></h3>
  </div>
</div>



<h2>Add this event to your agenda<h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ground Trotters</title>
  <!--   <%= csrf_meta_tags %>
    <%= csp_meta_tag %> -->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/svg" href="/public/basketball-game.svg" />
  </head>

  <body>

      <div class = "banner" style="background-image:url(<%= image_path 'la-sunset.jpg'%>);">
        <div class= "banner-text">
          <h1>GROUND TROTTERS</h1>
          <h2>The First Nomad BasketBall Players Community</h2>
          <h3>Make your life a basketball legend!</h3>
        </div>
        <div class= "connect-text">
          <h2>Login</h2>
          <h3>Sign in</h3>
        </div>
      </div>

      <div class="navbar">
        <a><%= link_to "Concept", root_path %></a>
        <a><%= link_to "Members", root_path %></a>
        <a><%= link_to "Playgrounds", playgrounds_path %></a>
        <a><%= link_to "Events", events_path %></a>
      </div>

    <%= yield %>
      <div class="footer">
        <h1>MAKE YOUR LIFE A BASKET BALL LEGEND</h1>
        <h1>Ground Trotters</h1>
        <h2>This site was made by ©Lite Services</h2>
        <h2><%= link_to "www.lite-services.com"%></h2>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>

app/views/pages/contact.html.erb
<h1>Our first contact 🚀</h1>

app/views/pages/home.html.erb
<p>Devenez une légende du BasketBall Solo<p>
<p>En découvrant notre plateforme, vous pourrez rêver de devenir une légende du basket en affrontant un nombre incalculables d'adversaires et en rencontrant les meilleurs joueurs qui vous conviennent.<p>
<p>La communauté Ground Trotters est faite pour vous permettre de devenir un Nomade du BasketBall partout dans le monde.
Découvrez les playgrounds dans tous les pays, voyagez avec votre Team, boostez votre réputation, Devenez un Ground Trotters de légende, de la rue jusqu'en NBA!<p>

<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<select class="form-select" aria-label="Disabled select example" disabled>
  <option selected>What are you looking for?</option>
  <option value="1">Games</option>
  <option value="2">Tournaments</option>
  <option value="3">Dunk Contests</option>
  <option value="4">Trainings</option>
  <option value="5">Shoots Challenges</option>
</select>

app/views/playgrounds/_playground_card.html.erb
  <div class="card-playground">
    <%= link_to playground_path(playground) do %>
      <h2><%= playground.name %></h2>
      <h2><%= playground.image %></h2>
      <h2><%= playground.location %></h2>
      <h2><%= playground.events %></h2>
    <% end %>
  </div>

app/views/playgrounds/index.html.erb
<button type="button" class="btn btn-primary btn-lg"><%=link_to "Add a playground", new_playground_path%></button>

<div id="map"
     style="width: 50%; height: 400px; margin-left: auto; margin-right:auto;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class ="container-1">
  <% @playgrounds.each do |playground| %>
  <%= render "playground_card", playground: playground %>
  <% end %>
</div>

app/views/playgrounds/new.html.erb
<h1 class="text-center">New Playground</h1>

<div class="pt-30 container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@playground) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :location %>
          <%= f.input :reputation %>
          <%= f.input :status %>
          <%= f.input :photo, as: :file %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
  <a class="link"><%=link_to "Home", root_path%></a>
</div>

app/views/playgrounds/show.html.erb
<a class="link"><%=link_to "Home", root_path%></a>
<a class="link"><%=link_to "Playgrounds", playgrounds_path%></a>
<a class="link"><%=link_to "Events", events_path%></a>

<h1><%= @playground.name %></h1>
<h1><%= @playground.status %></h1>

<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><h1><%= @playground.name %></h1></h5>
    <p class="card-text"><h1><%= @playground.reputation %><%= @playground.location %></h1></p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<%= @events %>
<%= @event %>

app/views/profiles/edit.html.erb
<h1><%= "Edition de profil" %></h1>
<a class="link"><%=link_to "Home", root_path%></a>


<select class="form-select" aria-label="Disabled select example" disabled>
  <option selected>What is your level?</option>
  <option value="1">Kid</option>
  <option value="2">Bad Boy</option>
  <option value="3">Uncle</option>
  <option value="4">Mamba</option>
  <option value="5">Street Legend</option>
</select>

<select class="form-select" aria-label="Disabled select example" disabled>
  <option selected>Which player are you?</option>
  <option value="1">Lonely Player</option>
  <option value="2">Teamate</option>
  <option value="3">Coach</option>
</select>

<select class="form-select" aria-label="Disabled select example" disabled>
  <option selected>What is your job player</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
  <option value="4">Four</option>
  <option value="5">Five</option>
</select>

app/views/profiles/show.html.erb
<h1><%= "Page de profil" %></h1>
<h1><%= link_to "Edition de profil", edit_profile_path %></h1>
<a class="link"><%=link_to "Home", root_path%></a>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>


<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>